### Question 1


In [49]:
import numpy as np
# A row vector (1D)
v1 = np.arange(0, 54, 1).reshape(6, 9)
print(v1)

# or
v2=np.random.randint(1, 50, size=(6, 6))
print(v2)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]]
[[19 44 40  8 45 41]
 [45 18 41 18 48 47]
 [ 9 48 29 24 27 18]
 [33 18 49 20 27  5]
 [ 4  1 25 49 13 46]
 [24  5 12  6 26 45]]


## Question 2


In [41]:
print("first Row:", v2[0])
print("second  Row:", v2[1])
print("sixth column:", v2[:, 5])
print("fifth column:", v2[:, 4])
print("fourth column:", v2[:, 3])

first Row: [46 14 47 28 20 48]
second  Row: [21  9 34 30  3 43]
sixth column: [48 43  9 11  7 33]
fifth column: [20  3 42 21 13  5]
fourth column: [28 30 17  8  4 49]


#### Question 3

In [54]:
trans= v2.reshape(3, 2, 6)
print("Transformed shape:\n" ,trans)

flatten= v2.flatten()
print("Flattened array:\n", flatten)

Transformed shape:
 [[[19 44 40  8 45 41]
  [45 18 41 18 48 47]]

 [[ 9 48 29 24 27 18]
  [33 18 49 20 27  5]]

 [[ 4  1 25 49 13 46]
  [24  5 12  6 26 45]]]
Flattened array:
 [19 44 40  8 45 41 45 18 41 18 48 47  9 48 29 24 27 18 33 18 49 20 27  5
  4  1 25 49 13 46 24  5 12  6 26 45]


#### Question 4

In [76]:
v3= np.random.randint(1, 40, size= (4, 4))
v3[np.arange(4), np.arange(4)] = [10, 20, 30, 40]
print(v3)



[[10 22 14  8]
 [ 6 20 31 12]
 [27 34 30 14]
 [19 28 33 40]]


In [75]:
 v4=np.eye(4)
 np.fill_diagonal(v4, [10, 20, 30, 40])
 print(v4)

[[10.  0.  0.  0.]
 [ 0. 20.  0.  0.]
 [ 0.  0. 30.  0.]
 [ 0.  0.  0. 40.]]


#### Question 5

In [ ]:
v5=np.random.randint(1, 10, size= (3, 4))
v6=np.random.randint(1, 10, size= (4, 3))

reshape=v6.reshape(3, 4)
print(v5)
print(reshape)
print("Multiplication:", v5*reshape)
# or
arraymulti= np.matmul(v5, v6)
print(arraymulti)



[[8 1 2 5]
 [8 2 8 5]
 [9 8 8 6]]
[[4 8 1 9]
 [1 6 7 9]
 [2 2 3 6]]
Multiplication: [[32  8  2 45]
 [ 8 12 56 45]
 [18 16 24 36]]
[[ 65  98  48]
 [116 153  66]
 [176 170 109]]


#### Question 6


In [ ]:
def arr_matrix():
  # Take the input for rows and columns from the user
  x = int(input("Please enter the number of rows: "))
  y = int(input("Please enter the number of columns: "))

  # Create a 2D NumPy array using the input from the user
  arr = np.arange(x * y).reshape(x, y)

  # Using the where function, return the squared even numbers and replace the odd numbers by -1
  new_arr = np.where(arr % 2 == 0, arr**2, -1)
  print(new_arr)
  
  # Output is a row of 3 and column of 4
  
arr_matrix()