### Matrix
```Question 1```

```Given The Following Matrices ```
```A=[2  -1 3] [0   4  1] and B=[1 2] [-2 0] [5 -3]``` 

1)Identify  the number of rows and columns in each matrix
2)Determine wether the matrices can be multiplied. if so,  specify weather it's (AB), (BA) or both
3)if the Multiplication is defined, compute the resulting matrix

#### Solution1

In [3]:
# 1) A= (2, 3)
#    B=  (3, 2)

import numpy as np
# Using Numpy to show
Matrix1=np.array([[2,-1, 3],
                  [0, 4 , 1]])


Matrix2 = np.array([[1, 2], 
                    [-2, 0],
                    [5 ,-3]])

print(Matrix1.shape)
Matrix2.shape

(2, 3)


(3, 2)

#### Solution 2

The two matrices can be multiplied, operation that can be performed is (AB) where A has same number of rows with columns in B. Both operations can be performed
        

#### solution 3

In [8]:
Matrix1=np.array([[2,-1, 3],
                  [0, 4 , 1]])


Matrix2 = np.array([[1, 2], 
                    [-2, 0],
                    [5 ,-3]])
AB_Multiplication=np.matmul(Matrix1, Matrix2)
print(AB_Multiplication)
BA_multi=np.matmul(Matrix2, Matrix1)
print(BA_multi)

[[19 -5]
 [-3 -3]]
[[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
