### 3.1

In [8]:
import numpy as np
import pandas as pd

# Representing Data in rows and 
data = {
    'Stuents': ['student 1', 'student 2', 'student 3', 'student 4'],
    'Math':    [80, 60 ,95 , 70],
    'English': [70, 85, 88, 60],
    'Science': [90, 75, 92, 65]}

DataR= pd.DataFrame(data)
DataR.head()






Stuents  Math  English  Science
0  student 1    80       70       90
1  student 2    60       85       75
2  student 3    95       88       92
3  student 4    70       60       65

### 3.2

In [ ]:
# representing data in array

student1= np.array([80,70, 90])
student2= np.array([60,85, 75])
student3= np.array([95,88, 92])
student4= np.array([70,60, 65])

student1
student2
student3
student4
# total
print("Total for student1:", np.sum(student1))
print("Total for student2:", np.sum(student2))
print("Total for student3:", np.sum(student3))
print("Total for student4:", np.sum(student4))




Total for student1: 240
Total for student2: 220
Total for student3: 275
Total for student4: 195


### 3.3

In [30]:
# Applying scaler multiplication, Making mathematics Twice important
# putting all in a column

students= np.array([[80,70, 90],
                    [60, 85, 75],
                    [95, 88, 92],
                    [70, 60, 65]
                    ])

print(students)
scaler_c= 2
# Making math twice important is scaler multiplication of maath column
# scaler_multi= np.dot(scaler_c, axis=1)

students_twice_math = students.copy()
students_twice_math[:, 0] = scaler_c * students_twice_math[:, 0]
print(students_twice_math)
Total= students_twice_math[:, 0].sum()
scale_x=students_twice_math[:, 0]
print("scaler Result:",scale_x)
print("scaler multiplication of math Total:", Total)


[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]
[[160  70  90]
 [120  85  75]
 [190  88  92]
 [140  60  65]]
scaler Result: [160 120 190 140]
scaler multiplication of math Total: 610


### 3.4

In [ ]:
students= np.array([[80,70, 90],
                    [60, 85, 75],
                    [95, 88, 92],
                    [70, 60, 65]
                    ])
Average_math= students[:,0].sum()/ 4
Average_eng= students[:, 1].sum()/ 4
Average_sci= students[:, 2].sum()/ 4

print(f"Average mathematics: {Average_math}")
print(f"Average English: {Average_eng}")
print(f"Average sci: {Average_sci}")

Average mathematics: 76.25
Average English: 75.75
Average sci: 80.5


### 3.5

In [57]:
students= np.array([[80,70, 90],
                    [60, 85, 75],
                    [95, 88, 92],
                    [70, 60, 65]
                    ])

weight_vector= np.array([[0.5], [0.3], [0.2]])

final_grade= np.matmul(students, weight_vector)
print(final_grade)

[[79. ]
 [70.5]
 [92.3]
 [66. ]]


### 3.6

In [47]:
# comparing scores of student1 3

Average_student1= students[2,:].sum()- students[0,:].sum()
print("difference in score vector:", Average_student1)

difference in score vector: 35


## Question five


In [9]:
data2= {
    'Stuents': ['student 1', 'student 2', 'student 3', 'student 4','student5'],
    'Math':    [91, 60 ,95 , 70, 80],
    'English': [70, 85, 87, 60, 70],
    'Science': [90, 40, 92, 65, 60],
    'chemistry': [30, 40, 89, 55, 40]}

DataR= pd.DataFrame(data2)
DataR.head()




Stuents  Math  English  Science  chemistry
0  student 1    91       70       90         30
1  student 2    60       85       40         40
2  student 3    95       87       92         89
3  student 4    70       60       65         55
4   student5    80       70       60         40

In [5]:
import numpy as np

array= np.array([
[91, 70 ,90 , 30,],
[60, 85, 40, 40,],
[95, 87, 92, 89,],
[70, 60, 65, 55,],
[80, 70, 60, 40]
])

array


array([[91, 70, 90, 30],
       [60, 85, 40, 40],
       [95, 87, 92, 89],
       [70, 60, 65, 55],
       [80, 70, 60, 40]])

In [33]:


print("Student1 total score:", array[0,:].sum())
print("Student2_total score:", array[1,:].sum())
print("Student3_total score:", array[2, :].sum())
print("Student4_total score:", array[3, :].sum())
print("Student 5_total score:", array[4, :].sum())


print("")

print("average student scores per subject")

print("Student 1 average score:", array[0, :].sum()/len(array[0,:]))
print("Student 2 average score:", array[1, :].sum()/len(array[1, :]))
print("Student 3 average score:", array[2, :].sum()/len(array[2, :]))
print("Student 4 average score:", array[3, :].sum()/len(array[3, :]))
print("Student 5 average score:", array[4, :].sum()/len(array[4, :]))




Student1 total score: 281
Student2_total score: 225
Student3_total score: 363
Student4_total score: 250
Student 5_total score: 250

average student scores per subject
Student 1 average score: 70.25
Student 2 average score: 56.25
Student 3 average score: 90.75
Student 4 average score: 62.5
Student 5 average score: 62.5


### Question 5.2

In [44]:
### If mathematics is 3 times as impoortant 
### scaler multiplication of Mathematics


scale_x=3
scaler_mul= np.dot(scale_x, array[:,0])

print("Scaler multiplication is ",scaler_mul)

print("Scaler multiplication of mathematics Total is", scaler_mul.sum())

Scaler multiplication is  [273 180 285 210 240]
Scaler multiplication of mathematics Total is 1188


### Question 5.3

In [59]:

# Create a new weight vector for grading:
# Math: 40%
# English: 20%
# Science: 30%
# Chemistry: 10%


weights = np.array([0.4, 0.2,0.3, 0.1])
final_grades = np.matmul(array, weights)
print(final_grades)

i=1
for grades in final_grades:
    print(f"Final Grades for student {i}:", grades)
    i+=1


[80.4 57.  91.9 65.  68. ]
Final Grades for student 1: 80.4
Final Grades for student 2: 57.0
Final Grades for student 3: 91.9
Final Grades for student 4: 65.0
Final Grades for student 5: 68.0


### Question 5.4

In [82]:
# Compare Student 3 and Student 4 using vector subtraction
student3 = np.array([95, 87, 92, 89])
student4 = np.array([70, 60, 65, 55])

subjects = ["Math", "English", "Science", "Chemistry"]
sub = student3 - student4
print("Difference (Student 3 - Student 4):", sub)

for idx, diff in enumerate(sub):
    if diff > 0:
        print(f"Student 3 performed better in {subjects[idx]} by {diff} points.")
    elif diff < 0:
        print(f"Student 4 performed better in {subjects[idx]} by {-diff} points.")
    else:
        print(f"Both students scored the same in {subjects[idx]}.")

Difference (Student 3 - Student 4): [25 27 27 34]
Student 3 performed better in Math by 25 points.
Student 3 performed better in English by 27 points.
Student 3 performed better in Science by 27 points.
Student 3 performed better in Chemistry by 34 points.
