In [1]:
import numpy as np


In [34]:
# given A=[2 -1]       and   B=[1  4]
        # [0  3]               [-2  5]

matrixA=np.array([[2 ,-1],
                 [0  , 3]])
matrixB=np.array([[1,   4],
                  [ -2 ,   5]])
c=2
d=3
# compute the following, cA,cB & (c+d)A
cA= matrixA*c
cB= matrixB*c
scaleadd= 5 * matrixA
print("cA:\n", cA)
print("cB:\n", cB)
print("(c+d)A:\n", scaleadd)




cA:
 [[ 4 -2]
 [ 0  6]]
cB:
 [[ 2  8]
 [-4 10]]
(c+d)A:
 [[10 -5]
 [ 0 15]]


### Question2

In [ ]:
# Verification of multiplication properties
# To verify Associativity (c*d)A=c*dA
# (cd)A= dopamine
Associativiy = c*d*matrixA
Associativiy2= d*matrixA*c
print("(c*d)A:\n",Associativiy)
print("c*dA:\n",Associativiy)
print("Therefore,(c*d)A=c*dA  ==True")
print("")


# distributivity over matrix add
# To prove that c(A+B)= cA+cB
distri1= matrixA+matrixB
disstric= 2*distri1
cA= 2 * matrixA
cB= 2 * matrixB
Addded= cA+cB

print("(A+B)c:\n",disstric)
print('')
print("cA+cB:\n", Addded)
print("")
print("Therefore,c(A+B)= cA+cB ==True")

# Distibutivity over over scaler add,
#   (c + d)A=cA + dA
scaled= c+d
scaledA= scaled * matrixA


cA= c * matrixA
dA= d * matrixA
cadded= cA + dA
print("(c+d)A:\n", scaledA)
print("")
print("cA +cB:\n", cadded)
print("therefore, (c + d)A=cA + dA== True ")


# Another approach
# cA_Computation = np.dot(c, matrixA)
# Ac_Computation = np.dot(matrixA, c)

# print(f"Associativity of Scalar Multiplication: {np.array_equal(cA, Ac)}")

# dB = np.dot(d, matrixB)
# Bd = np.dot(matrixB, d)
# print(f"Associativity of Scalar Multiplication: {np.array_equal(dB, Bd)}")
# cA= np.dot(c, matrixA)
# Ac= np.dot(matrixA, c)

# print(f"Associativity of Scalar Multiplication: {np.array_equal(cA, Ac)}")

# dB_Computation = np.dot(d, matrixB)
# Bd_Computation = np.dot(matrixB, d)
# print(f"Associativity of Scalar Multiplication: {np.array_equal(dB, Bd)}")


# #Distributivity over Scalar Addition
# left =  (c + d)*matrixA

# dA_computation = np.dot(d, matrixA)
# right = cA + dA
# print(f"Distributivity over Scalar Multiplication: {np.array_equal(left, right)}")








(c*d)A:
 [[12 -6]
 [ 0 18]]
c*dA:
 [[12 -6]
 [ 0 18]]
Therefore,(c*d)A=c*dA  ==True

(A+B)c:
 [[ 6  6]
 [-4 16]]

cA+cB:
 [[ 6  6]
 [-4 16]]

Therefore,c(A+B)= cA+cB ==True
(c+d)A:
 [[10 -5]
 [ 0 15]]

cA +cB:
 [[10 -5]
 [ 0 15]]


### Question3

In [52]:
# Find the transpose of the two

A_trans= matrixA.T
A_trans

B_trans= matrixB.T
print("A^T:\n", A_trans)
print("B^T:\n", B_trans)


A^T:
 [[ 2  0]
 [-1  3]]
B^T:
 [[ 1 -2]
 [ 4  5]]


### question 4

In [55]:
det_A = np.linalg.det(matrixA)
det_B = np.linalg.det(matrixB)


print("The determinant of matrix A is: \n", det_A)
print(f"matrix A Is invertible: {det_A != 0}\n") 

print("The determinant of matrix B : \n", det_B)
print(f"matrix B is Is invertible: {det_B != 0}\n")


# inverse
inverseA = np.linalg.inv(matrixA)
inverseB = np.linalg.inv(matrixB)
print(f"The inverse of matrix A is: \n {inverseA}")
print(f"\nThe inverse of matrix B is: \n {inverseB}")

The determinant of matrix A is: 
 6.0
matrix A Is invertible: True

The determinant of matrix B : 
 13.0
matrix B is Is invertible: True

The inverse of matrix A is: 
 [[0.5        0.16666667]
 [0.         0.33333333]]

The inverse of matrix B is: 
 [[ 0.38461538 -0.30769231]
 [ 0.15384615  0.07692308]]
